### ISSUE TITLE
how to input username/password for private registry ?

### ISSUE THREAD

**Issue by ctrongminh** [fraunhoferfokus/deckschrubber#13]
Hi,

The private registry requires username/password login
How do I input the username/password when executing the script ?

$GOPATH/bin/deckschrubber -registry https:/private.registry/repository/docker/ -tag latest -dry
FATA[0000] Error while fetching repositories! (err: unauthorized: access to the requested resource is not authorized)

Thanks

**Comment by yan-foto** [comment]
We don't support that ATM but @x-lhan is working on that. (see https://github.com/fraunhoferfokus/deckschrubber/pull/11)

**Comment by ctrongminh** [comment]
Thanks,
I'm looking forward to this.
