### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by phlegx** [fraunhoferfokus/deckschrubber#14]
First of all: Thanks for providing this binary!

Would be nice to have this in a ready to use docker image ;-)

**Comment by yan-foto** [comment]
Yes it would. It is also fairly easy to do that, but we are stuck ATM in a dead end due to some legal/bureaucratic issues (don't ask! 😅 )

**Comment by teneri66** [comment]
https://hub.docker.com/r/lhanxetus/deckschrubber/

**Comment by yan-foto** [comment]
Not from me, not up to date!

**Comment by marvinwankersteen** [comment]
Just add this `Dockerfile`:

```
# Stage: Build
FROM	golang:alpine as build

WORKDIR /go/src/deckschrubber

COPY	main.go main.go
COPY	types.go types.go
RUN	apk add --no-cache git && \
	go get -d -v  && \
	go install -v

# Stage: Run
FROM	alpine:latest
WORKDIR /root
COPY	--from=build /go/bin/deckschrubber .
RUN 	apk add --no-cache ca-certificates && \
	chmod +x deckschrubber
ENTRYPOINT ["/root/deckschrubber"]
```

`docker build --rm -t deckschrubber .`
`docker run --rm -ti deckschrubber --help`

The image has only 22 MByte.

**Comment by jgimenez** [comment]
We added a couple of things and made an image as well:
https://github.com/mobilejazz/deckschrubber
https://hub.docker.com/r/mobilejazz/deckschrubber

**Comment by yan-foto** [comment]
I'm closing this due to time shortage and I still consider it unnecessary to run a single executable in a relatively "bloated" virtual environment!
