### ISSUE TITLE
Disable SSL validation

### ISSUE THREAD

**Issue by Iyamoto** [fraunhoferfokus/deckschrubber#2]
Please add option to disable SSL certificate validation

**Comment by yan-foto** [comment]
I'm not gonna be able to take care of this in near future. But feel free to submit a pull request. The HTTP requests are done over Docker's API.

**Comment by sidietz** [comment]
I have no experience with go (either), but you can run 'deckschrubber' locally on the computer, which runs the docker-registry. This is done with the -registry switch like this: deckschrubber -registry http://localhost:5000 -dry

**Comment by HiranChaudhuri** [comment]
I have the same problem. My registry is running on https with a certificate from a private registry (not self-signed). Although the certificate is part of the OS truststore, deckschrubber complains about an unknown authority.

Either I need a way to provide a truststore, use the system truststore or turn off certificate validation. Deckschrubber is running on the same host as my registry and I do not see how that should resolve the http vs https issue.

**Comment by yan-foto** [comment]
@HiranChaudhuri What we do here is actually nothing else than using the standard [`crypto/tls`](https://pkg.go.dev/crypto/tls) module of Go lang. According to the [docs](https://pkg.go.dev/crypto/tls#Config):

```go
// If RootCAs is nil, TLS uses the host's root CA set.
```

So I suppose that your second alternative ("use the system truststore") is already the default behavior. If you need extra flexibility (e.g., custom cert, chain, etc.) I always welcome a PR.

**Comment by yan-foto** [comment]
> Please add option to disable SSL certificate validation

Note: the original request has been solved through introduction of `insecure` CLI flag.
