### ISSUE TITLE
Support for Bearer authentication

### ISSUE THREAD

**Issue by phertweck** [fraunhoferfokus/deckschrubber#26]
Thank you for this tool!

I'd like to use it to cleanup old images in our Gitlab-registry. Unfortunately it looks like we're using Bearer-Authentication which is not supported by the current version of deckschrubber. After passing username and password, I get the following exception:
`HEADERS: http.Header{"Www-Authenticate":[]string{"Bearer realm=\"https://ourgitlab.com/jwt/auth\",service=\"container_registry\",scope=\"registry:catalog:*\""}, "X-Content-Type-Options":[]string{"nosniff"}, "Server":[]string{"nginx"}, "D
ate":[]string{"Tue, 12 Mar 2019 11:53:35 GMT"}, "Content-Type":[]string{"application/json; charset=utf-8"}, "Content-Length":[]string{"145"}, "Connection":[]string{"keep-alive"}, "Docker-Distribution-Api-Version":[]string{"registry/2.0"}}
FATA[0002] Error while fetching repositories! (err: unauthorized: authentication required)
`

**Comment by yan-foto** [comment]
Duplicate: #1
