### ISSUE TITLE
Null pointer dereference error

### ISSUE THREAD

**Issue by jstoja** [fraunhoferfokus/deckschrubber#3]
Hello,

I'm trying to use this tool but I get a NPD from a basic command:
```
➜  ~ deckschrubber -registry https://user:pwd@my.registry.net/ -dry
INFO[0000] Successfully fetched repositories.            count=1 entries=[yolo]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x124cdcf]

goroutine 1 [running]:
github.com/docker/distribution/registry/api/v2.(*URLBuilder).BuildTagsURL(0xc420499080, 0x0, 0x0, 0xc42049d6b0, 0xc4203dd6f8, 0xc4203dd6b0, 0x1010a58)
	/Users/bordel/go/src/github.com/docker/distribution/registry/api/v2/urls.go:134 +0x6f
github.com/docker/distribution/registry/client.(*tags).All(0xc42049d5c0, 0x14375c0, 0x146cc40, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/bordel/go/src/github.com/docker/distribution/registry/client/repository.go:212 +0x92
main.main()
	/Users/bordel/go/src/github.com/fraunhoferfokus/deckschrubber/main.go:109 +0x97d
```

Do you have any idea?

**Comment by yan-foto** [comment]
It's the Docker API throwing the error 🤔 I should take it a look over there (is your username on your mac really `bordel` or are you just pulling my leg?)

**Comment by yan-foto** [comment]
I think I know whats happening here! Have you installed the package locally or used the binary from release page? I think there has been some changes to Docker APIs

**Comment by marcuslinke** [comment]
Found the same issue here. Will prepare a PR for the fix and some improvements if you like.

**Comment by jstoja** [comment]
I used the package locally, so it's probably what you think it is!

**Comment by yan-foto** [comment]
@marcuslinke did a great job. Will merge in coming days.
