### ISSUE TITLE
download problem

### ISSUE THREAD

**Issue by iosbeis** [fraunhoferfokus/deckschrubber#39]
Quick Installation failed
```
# go version
go version go1.16 linux/amd64
```

```
# go get github.com/fraunhoferfokus/deckschrubber
go: downloading github.com/fraunhoferfokus/deckschrubber v0.6.0
go: downloading github.com/docker/distribution v2.7.1+incompatible
go: downloading github.com/Sirupsen/logrus v1.8.0
go: downloading golang.org/x/crypto v0.0.0-20210220033148-5ea612d1eb83
go get: github.com/Sirupsen/logrus@none updating to
        github.com/Sirupsen/logrus@v1.8.0: parsing go.mod:
        module declares its path as: github.com/sirupsen/logrus
                but was required as: github.com/Sirupsen/logrus
```

**Comment by yan-foto** [comment]
It seems that a module name has been changed. Care to apply a PR?

**Comment by Shaked** [comment]
Same problem here. 

Just wondering, is this repo still maintained? Seems like a great tool

**Comment by yan-foto** [comment]
@Shaked thanks! It has been maintained sporadically since I don't use Docker anymore and no one seems to care enough to submit a PR!

**Comment by Shaked** [comment]
@yan-foto I might do that once I have the time. 

Out of curiosity, what are you using now if not Docker? Where can we discuss this outside Github issues?

**Comment by yan-foto** [comment]
@Shaked I moved away from Docker because it's not relevant anymore for me: I primarily used it for scalability of micro services and CI integration with GitLab; now I do neither :upside_down_face: so there's no secret Docker alternative that I could share with you :)

That being said, let me know if there's anything else that I could help with.

**Comment by Shaked** [comment]
> It seems that a module name has been changed. Care to apply a PR?

@yan-foto  

This has been fixed already: https://github.com/fraunhoferfokus/deckschrubber/commit/27d3a1e86ddbe10d4f1fab8a667f264f817af835 

However, `go get` still tries to pull the wrong version and the only way to overcome this problem at the moment is by running: 

```
go get -u github.com/fraunhoferfokus/deckschrubber@master
```

**Comment by yan-foto** [comment]
@Shaked any idea why that's the case? Does go get fetches the latest tag instead of latest master head?

**Comment by Shaked** [comment]
@yan-foto I think so. Could you create a new tag maybe?

**Comment by yan-foto** [comment]
Yes we can (™️)

**Comment by martin-1983** [comment]
First I want to thank you. Really appreciate your work and effort!

There was no progress for almost a month. Would be great if you could take care for tagging the latest version.

**Comment by yan-foto** [comment]
Sorry @sehlleier ! I'm fully booked here... But you're right, tagging shouldn't take much longer.

**Comment by yan-foto** [comment]
@Shaked @sehlleier did you guys come around to test this?

**Comment by martin-1983** [comment]
Yes, it works fine for me. Thank you very much!
