### ISSUE TITLE
Download problem

### ISSUE THREAD

**Issue by KaMaToZzz** [fraunhoferfokus/deckschrubber#40]
go get github.com/fraunhoferfokus/deckschrubber
package context: unrecognized import path "context" (import path does not begin with hostname)
package github.com/distribution/distribution/v3/reference: cannot find package "github.com/distribution/distribution/v3/reference" in any of:
	/usr/lib/go-1.6/src/github.com/distribution/distribution/v3/reference (from $GOROOT)
	/root/deckschrubber/src/github.com/distribution/distribution/v3/reference (from $GOPATH)
package github.com/distribution/distribution/v3/uuid: cannot find package "github.com/distribution/distribution/v3/uuid" in any of:
	/usr/lib/go-1.6/src/github.com/distribution/distribution/v3/uuid (from $GOROOT)
	/root/deckschrubber/src/github.com/distribution/distribution/v3/uuid (from $GOPATH)
package github.com/distribution/distribution/v3: cannot find package "github.com/distribution/distribution/v3" in any of:
	/usr/lib/go-1.6/src/github.com/distribution/distribution/v3 (from $GOROOT)
	/root/deckschrubber/src/github.com/distribution/distribution/v3 (from $GOPATH)
package github.com/distribution/distribution/v3/manifest: cannot find package "github.com/distribution/distribution/v3/manifest" in any of:
	/usr/lib/go-1.6/src/github.com/distribution/distribution/v3/manifest (from $GOROOT)
	/root/deckschrubber/src/github.com/distribution/distribution/v3/manifest (from $GOPATH)
package github.com/distribution/distribution/v3/digestset: cannot find package "github.com/distribution/distribution/v3/digestset" in any of:
	/usr/lib/go-1.6/src/github.com/distribution/distribution/v3/digestset (from $GOROOT)
	/root/deckschrubber/src/github.com/distribution/distribution/v3/digestset (from $GOPATH)
package github.com/distribution/distribution/v3/registry/api/errcode: cannot find package "github.com/distribution/distribution/v3/registry/api/errcode" in any of:
	/usr/lib/go-1.6/src/github.com/distribution/distribution/v3/registry/api/errcode (from $GOROOT)
	/root/deckschrubber/src/github.com/distribution/distribution/v3/registry/api/errcode (from $GOPATH)
package github.com/distribution/distribution/v3/registry/api/v2: cannot find package "github.com/distribution/distribution/v3/registry/api/v2" in any of:
	/usr/lib/go-1.6/src/github.com/distribution/distribution/v3/registry/api/v2 (from $GOROOT)
	/root/deckschrubber/src/github.com/distribution/distribution/v3/registry/api/v2 (from $GOPATH)
package github.com/distribution/distribution/v3/registry/client/auth/challenge: cannot find package "github.com/distribution/distribution/v3/registry/client/auth/challenge" in any of:
	/usr/lib/go-1.6/src/github.com/distribution/distribution/v3/registry/client/auth/challenge (from $GOROOT)
	/root/deckschrubber/src/github.com/distribution/distribution/v3/registry/client/auth/challenge (from $GOPATH)
package github.com/distribution/distribution/v3/registry/client/transport: cannot find package "github.com/distribution/distribution/v3/registry/client/transport" in any of:
	/usr/lib/go-1.6/src/github.com/distribution/distribution/v3/registry/client/transport (from $GOROOT)
	/root/deckschrubber/src/github.com/distribution/distribution/v3/registry/client/transport (from $GOPATH)
package github.com/distribution/distribution/v3/registry/storage/cache: cannot find package "github.com/distribution/distribution/v3/registry/storage/cache" in any of:
	/usr/lib/go-1.6/src/github.com/distribution/distribution/v3/registry/storage/cache (from $GOROOT)
	/root/deckschrubber/src/github.com/distribution/distribution/v3/registry/storage/cache (from $GOPATH)
package github.com/distribution/distribution/v3/registry/storage/cache/memory: cannot find package "github.com/distribution/distribution/v3/registry/storage/cache/memory" in any of:
	/usr/lib/go-1.6/src/github.com/distribution/distribution/v3/registry/storage/cache/memory (from $GOROOT)
	/root/deckschrubber/src/github.com/distribution/distribution/v3/registry/storage/cache/memory (from $GOPATH)
package math/bits: unrecognized import path "math/bits" (import path does not begin with hostname)

**Comment by yan-foto** [comment]
Does not contain any explanation.
