### ISSUE TITLE
SSO auth issue

### ISSUE THREAD

**Issue by phlegx** [fraunhoferfokus/deckschrubber#42]
It seems that when I run my registry server with SSO Auth (via Keycloak) then Deckschrubber cannot authenticate. The error I get is:

```
deckschrubber -registry $REGISTRY_URL -user $REGISTRY_USERNAME -password $REGISTRY_PASSWORD -repos=9999 -latest 3 
FATA[0000] Error while fetching repositories! (err: unauthorized: authentication required)
```

In my registry server the error is:

```
^[[1;5Ftime="2021-06-24T11:35:40.647713286Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.11.2 http.request.host=registry.example.com http.request.id=xxxxxx http.request.method=GET http.request.remoteaddr=xxx.xx.xxx.xxx http.request.uri="/v2/_catalog?n=9999" http.request.useragent="Go-http-client/1.1" 
172.20.0.6 - - [24/Jun/2021:11:35:40 +0000] "GET /v2/_catalog?n=9999 HTTP/1.0" 401 145 "" "Go-http-client/1.1"
```

Is this a known issue and if yes, will this be solved at some point?

best
Martin

**Comment by yan-foto** [comment]
duplicate #1

**Comment by yan-foto** [comment]
Hey Martin, I just added a solution that might solve you're problem (see my comment on #1). Maybe you could give it a try and let me know how that works. Any contribution is very welcome here!

**Comment by phlegx** [comment]
Thanks @yan-foto ! I will try it out in the next days and get back to you!
