### ISSUE TITLE
Deleting a tag also deletes all other images with this image ID.

### ISSUE THREAD

**Issue by aboettger-tuhh** [fraunhoferfokus/deckschrubber#9]
I have one image with three tags

```
docker/moodle:latest
docker/moodle:12376
docker/moodle:3.2-stable
```
The command
```
deckschrubber -registry "${REGISTRY}" -tag '^\d+$' -repo docker/moodle -latest 1 -repos 999
```
deletes the Image. Is it possible to delete an image only if there is only one tag?

**Comment by yan-foto** [comment]
I really don't get the question. Which one do you want to delete and which ones do you want to keep?
